SELECT * FROM ACCOUNT;

DELETE FROM PASS;

DELETE FROM PASS WHERE ID='ONG001';
DELETE FROM PASS WHERE PASSCODE='ONG00120180903';
DELETE FROM CODESET WHERE PASSCODE='ONG00120180903';
DELETE FROM RECORDILJI WHERE PASSCODE='ONG00120180903';

SELECT * FROM RECORDILJI WHERE PASSCODE LIKE'ONG001%';

DELETE FROM CODESET WHERE PASSCODE='ONG00120180903';

SELECT MAX(ILLYUNG) FROM CODESET  WHERE PASSCODE='ONG00120181101';

UPDATE PASS SET DELFLAG='N' WHERE PASSCODE='TEST20181110';

SELECT * FROM PASS WHERE ID='ONG001';

SELECT * FROM PASS WHERE PASSCODE='ONG00120181003';
SELECT * FROM CODESET WHERE PASSCODE='ONG00120181003';
SELECT * FROM RECORDILJI WHERE PASSCODE='ONG00120181003';

UPDATE PASS SET DELFLAG='Y' WHERE PASSCODE='ONG00120180903';
UPDATE CODESET SET DELFLAG='Y' WHERE PASSCODE='ONG00120180903';
UPDATE RECORDILJI SET DELFLAG='Y' WHERE PASSCODE='ONG00120180903';


DELETE FROM PASS WHERE PASSCODE='ONG00120181110';
DELETE FROM CODESET  WHERE PASSCODE='ONG00120181110';
DELETE FROM PASS WHERE PASSCODE='ONG00120181111';
DELETE FROM CODESET  WHERE PASSCODE='ONG00120181111';

SELECT PASSCODE, STARTPASS, ENDPASS, INCOUNT, INDUM, INTYPE, INBUHWA, INACTIVITY, DONGCHICKNUM FROM PASS
WHERE ID = 'ONG001' AND DELFLAG='N';

UPDATE PASS SET DELFLAG='N' WHERE PASSCODE='ONG00120181101';

UPDATE PASS SET ENDPASS='20181215' WHERE PASSCODE='ONG00120181101';

SELECT * FROM CODESET WHERE PASSCODE='ONG00120181101';

SELECT TO_CHAR(TO_DATE('2018-11-01'),'YYYYMMDD') FROM DUAL;


SELECT PASSCODE, ILLYUNG, TO_CHAR(RECORDDATE,'YYYY-MM-DD'), DEATHCOUNT, DISTINCTDONG
FROM RECORDILJI
WHERE DEATHCOUNT IS NOT NULL
AND REGEXP_LIKE(DISTINCTDONG, '[1-9]')
ORDER BY ILLYUNG, DISTINCTDONG ASC;



SELECT DEATHCOUNT, WEIGHT, DISTINCTDONG
FROM RECORDILJI
WHERE PASSCODE='ONG00120181003' AND DELFLAG='N' AND DISTINCTDONG LIKE '%2%';




SELECT 1 AS DISTINCTDONG, SUM(DEATHCOUNT) AS DEATHCOUNT,0 AS WEIGHT
	FROM RECORDILJI
	WHERE PASSCODE='ONG00120181003' AND DELFLAG='N'
		AND DISTINCTDONG LIKE '%1%';

SELECT 1 AS DISTINCTDONG, 0 AS DEATHCOUNT,AVG(WEIGHT) AS WEIGHT
	FROM RECORDILJI
	WHERE PASSCODE='ONG00120181003' AND DELFLAG='N'
		AND WEIGHT>0 AND DISTINCTDONG LIKE '%1%';
	
	
	
SELECT 1 AS DISTINCTDONG, SUM(DEATHCOUNT),SUM(WEIGHT)
FROM (SELECT SUM(DEATHCOUNT) AS DEATHCOUNT,0 AS WEIGHT
		FROM RECORDILJI
		WHERE PASSCODE='ONG00120181003' AND DELFLAG='N'
			AND DISTINCTDONG LIKE '%1%'
	UNION
	SELECT 0 AS DEATHCOUNT,AVG(WEIGHT) AS WEIGHT
		FROM RECORDILJI
		WHERE PASSCODE='ONG00120181003' AND DELFLAG='N'
			AND WEIGHT>0 AND DISTINCTDONG LIKE '%1%');


SELECT 2 AS DISTINCTDONG, SUM(DEATHCOUNT),SUM(WEIGHT)
FROM (SELECT SUM(DEATHCOUNT) AS DEATHCOUNT,0 AS WEIGHT
		FROM RECORDILJI
		WHERE PASSCODE='ONG00120181003' AND DELFLAG='N'
			AND DISTINCTDONG LIKE '%2%'
	UNION
	SELECT 0 AS DEATHCOUNT,AVG(WEIGHT) AS WEIGHT
		FROM RECORDILJI
		WHERE PASSCODE='ONG00120181003' AND DELFLAG='N'
			AND WEIGHT>0 AND DISTINCTDONG LIKE '%2%');



FROM (SELECT SUM(DEATHCOUNT) AS DEATHCOUNT,0 AS WEIGHT
	FROM RECORDILJI
	WHERE PASSCODE='ONG00120181003' AND DELFLAG='N'
		AND DISTINCTDONG LIKE '%1%'
	UNION
	SELECT 0 AS DEATHCOUNT,AVG(WEIGHT) AS WEIGHT
	FROM RECORDILJI
	WHERE PASSCODE='ONG00120181003' AND DELFLAG='N'
		AND WEIGHT>0 AND DISTINCTDONG LIKE '%1%');




SELECT PASSCODE, ID, TO_CHAR(STARTPASS,'YYYYMMDD'), TO_CHAR(ENDPASS,'YYYYMMDD'), INCOUNT, INDUM, INTYPE, INBUHWA, INACTIVITY, DONGCHICKNUM
	FROM PASS WHERE PASSCODE='ONG00120180903' AND DELFLAG='N';

SELECT RECORDILJI_SEQ, PASSCODE, ILLYUNG, HIGHTEMP, LOWTEMP, RECORDDATE, RECORDTIME, MEDICINE, WEATHERCON, ETC, DEATHCOUNT, WEIGHT, BUILDTEMP, DISTINCTDONG
FROM RECORDILJI WHERE PASSCODE='ONG00120180903' AND DELFLAG='N' ORDER BY RECORDILJI_SEQ;




INSERT INTO ACCOUNT
(ID, PW, EMAIL, PHONE, ADDRESS, NAME, FARMNAME, FARMADDRESS, FARMTEL, DONGNUMBER, RECENTDATE, AUTH, DELFLAG)
VALUES('ONG001', '1234', 'ONG@KKOKIO.COM', '010-1234-5678', 'HERE',
		'옹성우', '옹성우네농장', '02-123-1234', '2', 2 , SYSDATE , 'U' , 'N' );

INSERT INTO PASS
(PASSCODE, ID, STARTPASS, ENDPASS, INCOUNT, INDUM, INTYPE, INBUHWA, INACTIVITY, DONGCHICKNUM, DELFLAG)
VALUES('ONG001'||TO_CHAR(SYSDATE,'YYYYMMDD'), 'ONG001', '20180903', '20180930', 37360, 1121, '하바드','' ,'상', '18760/18600', 'N' );


SELECT TO_CHAR(SYSDATE,'YYYYMMDD') FROM DUAL;

SELECT SUBSTR('ILJI001',5) FROM DUAL;

SELECT 'ILJI'||TO_CHAR(1,'0999') FROM DUAL;
SELECT REPLACE('ILJI'||TO_CHAR(ILJI_SEQ.NEXTVAL,'0999'),' ','') FROM DUAL;



SELECT PASSCODE,STARTPASS, ENDPASS, ENDPASS-STARTPASS+1  FROM PASS WHERE PASSCODE='TEST20181110';
SELECT PASSCODE,STARTPASS, ENDPASS, ENDPASS-STARTPASS+1  FROM PASS;

INSERT INTO CODESET
(PASSCODE, ILLYUNG, DELFLAG)
VALUES('', 0, 'N' );


SELECT PRODUCTCODE, PNAME, PPRICE, PDETAIL, DELFLAG
FROM PRODUCT;

SELECT PURCHASECODE, PASSCODE, ILLYUNG, PRODUCTCODE, PRODUCTIN, PRODUCTNUM, ETC, DELFLAG
FROM PURCHASE;



SELECT PRODUCTCODE, PNAME, PPRICE, PDETAIL, PURCHASECODE, PASSCODE, ILLYUNG, PRODUCTIN, PRODUCTNUM, ETC
FROM PRODUCT JOIN PURCHASE USING(PRODUCTCODE)
WHERE PRODUCT.DELFLAG IS NOT NULL AND PURCHASE.DELFLAG IS NOT NULL;


