
SELECT ISSUECODE, RECORDILJI_SEQ, PASSCODE, ILLYUNG, CONTENTCODE, ACTIONCODE, ISSUEDETAIL, ACTIONDETAIL, ISSUEETC, ACTIONRESULT, DELFLAG
FROM ISSUE;

DELETE FROM ISSUE;

--이슈사항 글 등록
--RECORDILJI_SEQ, PASSCODE, ILLYUNG, ISSUEDETAIL, ISSUEETC
INSERT INTO ISSUE
(ISSUECODE, RECORDILJI_SEQ, PASSCODE, ILLYUNG, CONTENTCODE, ACTIONCODE, ISSUEDETAIL, ISSUEETC, ACTIONRESULT, DELFLAG)
VALUES('IS'||ISSUE_SEQ.NEXTVAL,'ILJI46','ONG00120180903', 1, 'IS'||ISSUE_SEQ.NEXTVAL,0, '사육장 온도가 너무 높아요','', 'N' , 'N' );


--이슈사항 글 수정
UPDATE ISSUE
SET ISSUEDETAIL='사육장 온도가 너무 높아요_수정', ISSUEETC=''
WHERE ISSUECODE='IS30';

--이슈사항/조치사항 결과 수정
UPDATE ISSUE
SET ACTIONRESULT='Y' 
WHERE CONTENTCODE='IS30';



--이슈사항 글 삭제 --하위 글(조치사항)도 전부 삭제
UPDATE ISSUE
SET DELFLAG='Y'
WHERE CONTENTCODE='IS30';

--이슈사항 / 조치사항 전체조회
SELECT ISSUECODE, RECORDILJI_SEQ, PASSCODE, ILLYUNG, CONTENTCODE, ACTIONCODE, ISSUEDETAIL, ACTIONDETAIL, ISSUEETC, ACTIONRESULT, DELFLAG
FROM ISSUE
WHERE DELFLAG='N'
ORDER BY CONTENTCODE DESC, ACTIONCODE ASC;

--이슈사항 /조치사항 상세조회
SELECT ISSUECODE, RECORDILJI_SEQ, PASSCODE, ILLYUNG, CONTENTCODE, ACTIONCODE, ISSUEDETAIL, ACTIONDETAIL, ISSUEETC, ACTIONRESULT, DELFLAG
FROM ISSUE
WHERE ISSUECODE='IS30' AND DELFLAG='N';


--조치사항 글 등록

UPDATE ISSUE
SET ACTIONCODE = ACTIONCODE+1
WHERE ISSUECODE IN (SELECT ISSUECODE FROM ISSUE
WHERE CONTENTCODE='IS30' AND ACTIONCODE>0);

INSERT INTO ISSUE
(ISSUECODE, RECORDILJI_SEQ, PASSCODE, ILLYUNG, CONTENTCODE, ACTIONCODE, ACTIONDETAIL, ISSUEETC, ACTIONRESULT, DELFLAG)
VALUES('IS'||ISSUE_SEQ.NEXTVAL,'ILJI46','ONG00120180903', 1, 'IS30',
1,
'환풍기 다시 작동 시킴_2','', 'N' , 'N' );

--조치사항 수정
UPDATE ISSUE
SET ACTIONDETAIL='환풍기 강도 높임', ISSUEETC='온도가 조금 내려가는 듯 하다'
WHERE ISSUECODE='IS32';



--조치사항 삭제
UPDATE ISSUE
SET DELFLAG='Y'
WHERE ISSUECODE='IS32';






DELETE FROM ISSUE;


SELECT * FROM PASS;

SELECT PASSCODE, STARTPASS, INCOUNT, INDUM, INTYPE, INBUHWA, INACTIVITY, DONGCHICKNUM
FROM PASS WHERE PASSCODE='Farmer1220181110' AND DELFLAG='N';


SELECT DEATHCOUNT, DISTINCTDONG
FROM RECORDILJI WHERE PASSCODE='Farmer1220181110' AND DEATHCOUNT IS NOT NULL AND DELFLAG='N';

SELECT SUM(DEATHCOUNT)
FROM RECORDILJI WHERE PASSCODE='Farmer1220181110' AND DEATHCOUNT IS NOT NULL AND DELFLAG='N'
AND DISTINCTDONG='1';
