CREATE TABLE TYPETABLE(
ID VARCHAR2(20) PRIMARY KEY,
BIRTHDAY DATE,
SHOES NUMBER,
GENDER CHAR
);


SELECT ID, BIRTHDAY, SHOES, GENDER
FROM TYPETABLE;

SELECT * FROM TYPETABLE;

INSERT INTO TYPETABLE
(ID, BIRTHDAY, SHOES, GENDER)
VALUES('ONG1', '20181112', 8, 'M');

UPDATE TYPETABLE
SET SHOES=3
WHERE ID='ONG1';


DELETE FROM TYPETABLE
WHERE ID='ONG1';
