DROP TABLE ADDRESSCODE;

CREATE TABLE ADDRESSCODE(
	ID VARCHAR2(20) PRIMARY KEY,
	ADDRESSCODE NUMBER,
	DELFLAG CHAR DEFAULT 'N',
	CONSTRAINT FK_ID FOREIGN KEY(ID) REFERENCES ACCOUNT(ID)
);




SELECT * FROM ACCOUNT;
SELECT * FROM ADDRESSCODE;

INSERT INTO ADDRESSCODE
(ID, ADDRESSCODE, DELFLAG)
VALUES('ONG001', 1234, 'N');

UPDATE ADDRESSCODE
SET ADDRESSCODE=4321
WHERE ID='ONG001';

SELECT ADDRESSCODE
FROM ADDRESSCODE
WHERE ID='ONG001' AND DELFLAG='N';


DELETE FROM ADDRESSCODE;
