SELECT * FROM HAPPYMEMBER;
SELECT * FROM HAPPYBOARD;

SELECT SEQ, ID, TITLE, CONTENT, REFER, STEP, "DEPTH", READCOUNT, DELFLAG, REGDATE
FROM HAPPYBOARD;

SELECT ID, PW, NAME, AUTH, DELFLAG, REGDATE
FROM HAPPYMEMBER;


SELECT SEQ, ID, TITLE, CONTENT, REFER, STEP, "DEPTH", READCOUNT, PW, NAME, AUTH, HAPPYBOARD.REGDATE
FROM HAPPYBOARD JOIN HAPPYMEMBER USING(ID)
WHERE HAPPYBOARD.DELFLAG IS NOT NULL AND HAPPYMEMBER.DELFLAG IS NOT NULL;