SELECT RECORDILJI_SEQ, PASSCODE, ILLYUNG, HIGHTEMP, LOWTEMP, RECORDDATE, RECORDTIME, MEDICINE, WEATHERCON, ETC, DEATHCOUNT, WEIGHT, BUILDTEMP, DISTINCTDONG
FROM RECORDILJI WHERE PASSCODE LIKE 'ONG001%' AND DELFLAG='N';


SELECT RECORDILJI_SEQ, PASSCODE, ILLYUNG, HIGHTEMP, LOWTEMP, RECORDDATE, RECORDTIME, MEDICINE, WEATHERCON, ETC, DEATHCOUNT, WEIGHT, BUILDTEMP, DISTINCTDONG
FROM RECORDILJI
WHERE PASSCODE LIKE 'ONG001201802%'
AND ILLYUNG='1'
AND DELFLAG='N';


SELECT RECORDILJI_SEQ, PASSCODE, ILLYUNG, HIGHTEMP, LOWTEMP, RECORDDATE, RECORDTIME, MEDICINE, WEATHERCON, ETC, DEATHCOUNT, WEIGHT, BUILDTEMP, DISTINCTDONG
FROM RECORDILJI
WHERE PASSCODE LIKE 'ONG001201802%'
AND ILLYUNG='1'
AND (DISTINCTDONG LIKE '%1%'
	OR DISTINCTDONG LIKE '%2%') 
AND DELFLAG='N';


