SELECT RECORDILJI_SEQ, PASSCODE, ILLYUNG, DEATHCOUNT, WEIGHT, BUILDTEMP, ETC, MEDICINE, DISTINCTDONG, RECORDTIME
FROM RECORDILJI
WHERE PASSCODE = 'ONG00120181003'
AND DELFLAG = 'N'
AND ILLYUNG = '1'
ORDER BY DISTINCTDONG;

SELECT * FROM RECORDILJI WHERE PASSCODE='ONG00120181003' AND ILLYUNG='1';

INSERT INTO RECORDILJI
(RECORDILJI_SEQ, PASSCODE, ILLYUNG, HIGHTEMP, LOWTEMP, RECORDDATE, RECORDTIME, MEDICINE, WEATHERCON, ETC, DEATHCOUNT, WEIGHT, BUILDTEMP, DISTINCTDONG, DELFLAG)
VALUES('ILJI'||ILJI_SEQ.NEXTVAL, 'ONG00120181003', 1, 0, 0, SYSDATE, SYSDATE, '', '', '', 10, 0, 0, '2', 'N' );


SELECT COUNT(*) FROM PASS WHERE PASSCODE='ONG00120180203';
SELECT COUNT(*) FROM PASS WHERE PASSCODE='ONG00120180213';

SELECT COUNT(*) FROM PASS WHERE PASSCODE=#{passcode}
