SELECT RECORDILJI_SEQ,ILLYUNG,DEATHCOUNT,DISTINCTDONG FROM RECORDILJI WHERE PASSCODE='ONG00120180203' AND DELFLAG='N' AND DEATHCOUNT>0;
INSERT INTO RECORDILJI
(RECORDILJI_SEQ, PASSCODE, ILLYUNG, HIGHTEMP, LOWTEMP, RECORDDATE, RECORDTIME, MEDICINE, WEATHERCON, ETC, DEATHCOUNT, WEIGHT, BUILDTEMP, DISTINCTDONG, DELFLAG)
VALUES('ILJI'||ILJI_SEQ.NEXTVAL, 'ONG00120180203', 1, 0, 0, '', SYSDATE,SYSDATE, '', '', 0, 0, 0, '', 'N');


SELECT ILLYUNG,NVL(DISTINCTDONG,'동합계') AS DISTINCTDONG,SUM(DEATHCOUNT) AS DEATHCOUNT
FROM RECORDILJI
WHERE PASSCODE='ONG00120160606' AND DELFLAG='N' AND DEATHCOUNT>0
GROUP BY ROLLUP(ILLYUNG,DISTINCTDONG)
ORDER BY ILLYUNG,DISTINCTDONG;

SELECT * FROM RECORDILJI WHERE DEATHCOUNT>0;

SELECT ILLYUNG,NVL(DISTINCTDONG,'동합계') AS DISTINCTDONG,SUM(DEATHCOUNT) AS DEATHCOUNT
FROM RECORDILJI
WHERE PASSCODE='farmer720181201' AND DELFLAG='N' AND DEATHCOUNT>0
GROUP BY ROLLUP(ILLYUNG,DISTINCTDONG)
ORDER BY ILLYUNG,DISTINCTDONG;
