SELECT DISTINCTDONG FROM RECORDILJI WHERE RECORDILJI_SEQ='ILJI46';

SELECT * FROM RECORDILJI;

SELECT * FROM RECORDILJI WHERE DISTINCTDONG LIKE '%1%';
SELECT * FROM RECORDILJI WHERE DISTINCTDONG LIKE '%2%';
SELECT * FROM RECORDILJI WHERE DISTINCTDONG LIKE '%1%' OR DISTINCTDONG LIKE '%2%';

SELECT INSTR(DISTINCTDONG,'1',1,1) FROM RECORDILJI WHERE RECORDILJI_SEQ='ILJI46';


 SELECT distinct regexp_substr(A.DISTINCTDONG, '[^/]+', 1, LEVEL) DISTINCTDONG
   FROM (SELECT DISTINCTDONG FROM RECORDILJI WHERE RECORDILJI_SEQ='ILJI46') A
CONNECT BY LEVEL <= length(regexp_replace(A.DISTINCTDONG, '[^/]+',''))+1;



 SELECT distinct regexp_substr(A.DISTINCTDONG, '[^/]+', 1, LEVEL) DISTINCTDONG
   FROM (SELECT '1/2/4' DISTINCTDONG FROM DUAL) A
CONNECT BY LEVEL <= length(regexp_replace(A.DISTINCTDONG, '[^/]+',''))+1;


------
 SELECT distinct regexp_substr(DISTINCTDONG, '[^/]+', 1, LEVEL) DISTINCTDONG
   FROM RECORDILJI
   WHERE RECORDILJI_SEQ='ILJI46'
	CONNECT BY LEVEL <= length(regexp_replace(DISTINCTDONG, '[^/]+',''))+1;
--------


 SELECT distinct regexp_substr(A.TXT, '[^|]+', 1, LEVEL) TXT
   FROM (SELECT 'A|B|C|D' TXT FROM dual) A
CONNECT BY LEVEL <= length(regexp_replace(A.TXT, '[^|]+',''))+1;

 SELECT substr(A.TXT,
              instr(A.TXT, '|', 1, LEVEL) + 1,
              instr(A.TXT, '|', 1, LEVEL + 1) - instr(A.TXT, '|', 1, LEVEL) - 1) TXT
   FROM (SELECT '|' || 'A|B|C|D' || '|' TXT FROM dual) A
CONNECT BY LEVEL <= length(A.TXT) - length(REPLACE(A.TXT, '|')) - 1;